[build-system]
requires = ["setuptools>=75", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "cf_dataloader"
readme = "README.md"
requires-python = ">=3.9,<3.13"
version = "0.0.1"
dependencies = [
    "numpy ~= 1.26",
    "ase",
    "torch",
    "tqdm",
]
